About us page
ReCoded-Org/capstone-turkey-animal-adoption pull request #31
Opened 2021-08-22 21:38 UTC by ayse8888

Hi,
I built About Us Page
@halitbatur here I have some notes about the page.
1. In the header section, right / left works on Mustafa's side but does not work on my side when i change left to right. We tried more than 1 hour but could not make it work. Not to lose any more time since we have many missing parts , I chose another picture here for left side as attached.
![image](https://user-images.githubusercontent.com/65858467/130370653-10cf8f70-d4a1-4f23-8d74-e7e68aa9f26a.png)

2. In the next section, I mentioned you I am not able to change the modal content completely since it is coming from a merged component and unfortunately I used partial props there. And not to break any code, I did not change the data from the merged component but if that's ok, I can change. The thing I wanted to put was some articles here but I had to change it as "latest adoptions" to make it fit to the structure.
![image](https://user-images.githubusercontent.com/65858467/130370699-f7316b84-8052-470f-ade2-e89d307a1598.png)
![image](https://user-images.githubusercontent.com/65858467/130370708-e1629a5b-29c8-4a99-b0a0-9ccbaff8771d.png)

3. I changed some little css from a merged component when i am in about-us-page branch as per my conversation with you since there was duplicate class names.

4. And finally the team part is below
![image](https://user-images.githubusercontent.com/65858467/130370769-94a0fd0b-4c2a-41c3-ba17-8b9868ae34bb.png)

2021-08-23 07:07 UTC, halitbatur approved these changes

2021-08-23 07:07 UTC, halitbatur commented on src/pages/aboutus/teamdata.js
> +import React from "react";
can we move this to data folder ?

2021-08-23 07:07 UTC, halitbatur commented on src/pages/aboutus/worksdata.js
> +import poodle from "../../images/poodle.jpg";
can we move this to a data folder ?

2021-08-23 07:07 UTC, halitbatur requested changes
some few changes and then its ready

2021-08-23 16:36 UTC, ayse8888 commented on src/pages/aboutus/teamdata.js
> +import React from "react";
done

2021-08-23 16:36 UTC, ayse8888 commented on src/pages/aboutus/worksdata.js
> +import poodle from "../../images/poodle.jpg";
done

2021-08-24 08:01 UTC, halitbatur approved these changes
Looks good to me Ayse good work !

2021-08-24 08:15 UTC, halitbatur commented
@ayse8888 could u updated this branch and resolve conflicts ?

2021-08-24 12:05 UTC, mustafaguldag approved these changes
Hi Ayşe, it seems nice to me. There is no unnesesary spaces. Thank you for your contribute!

2021-08-25 07:01 UTC, merged