Search component
ReCoded-Org/capstone-turkey-animal-adoption pull request #32
Opened 2021-08-22 23:12 UTC by ayse8888

Hi,
I built Search Component #23 
Below is my visuals
I used formik Yup for form validation.

1. when page loads
![image](https://user-images.githubusercontent.com/65858467/130372919-248d3298-9a94-4b90-9490-d92c0d81748a.png)

2. when user makes a search
![image](https://user-images.githubusercontent.com/65858467/130372933-0a2b1a56-73a5-4225-81b6-717af3757eb4.png)

3. when there is no items matching
![image](https://user-images.githubusercontent.com/65858467/130372947-921418b2-057f-43a7-ba54-d6762c0c8f51.png)

4. when user clicks adopts button
![image](https://user-images.githubusercontent.com/65858467/130372965-04ff9885-40b2-4437-b891-7a6016dbec64.png)

5. when form submitted
![image](https://user-images.githubusercontent.com/65858467/130372980-abbd844d-8723-4212-ba34-a8832feeed86.png)

2021-08-23 07:08 UTC, halitbatur commented
@ayse8888 please update branch and fix conflicts

2021-08-24 08:02 UTC, halitbatur requested changes

2021-08-24 08:02 UTC, halitbatur commented on src/components/Search/AdoptionFormModal.js
> +          validationSchema={Yup.object({
can we move this to another variable and then call it here ?

2021-08-24 08:02 UTC, halitbatur commented on src/components/Search/AdoptionFormModal.js
> +
extra spaces

2021-08-24 08:02 UTC, halitbatur commented on src/components/Search/AdoptionFormModal.js
> +
extra new lines between components

2021-08-24 08:02 UTC, halitbatur commented on src/components/Search/AdoptionFormModal.js
> +
extra line between components

2021-08-24 08:02 UTC, halitbatur commented on src/components/Search/AdoptionFormModal.js
> +
extra new line

2021-08-24 08:02 UTC, halitbatur commented on src/components/Search/AdoptionFormModal.js
> +
extra new line

2021-08-24 08:02 UTC, halitbatur commented on src/components/Search/AdoptionFormModal.js
> +
extra new line

2021-08-24 08:02 UTC, halitbatur commented on src/components/Search/Search.js
> +
extra new line

2021-08-24 18:31 UTC, ayse8888 commented on src/components/Search/AdoptionFormModal.js
> +          validationSchema={Yup.object({
done

2021-08-24 18:31 UTC, ayse8888 commented on src/components/Search/AdoptionFormModal.js
> +
done

2021-08-24 18:31 UTC, ayse8888 commented on src/components/Search/AdoptionFormModal.js
> +
done

2021-08-24 18:31 UTC, ayse8888 commented on src/components/Search/AdoptionFormModal.js
> +
done

2021-08-24 18:31 UTC, ayse8888 commented on src/components/Search/AdoptionFormModal.js
> +
done

2021-08-24 18:31 UTC, ayse8888 commented on src/components/Search/AdoptionFormModal.js
> +
done

2021-08-24 18:31 UTC, ayse8888 commented on src/components/Search/AdoptionFormModal.js
> +
done

2021-08-24 18:31 UTC, ayse8888 commented on src/components/Search/Search.js
> +
done

2021-08-26 09:11 UTC, Rofy87 approved these changes
Thanks for the great work ayse

2021-08-26 09:32 UTC, mustafaguldag approved these changes
It looks solid Ayşe. Thanks for your contribute!

2021-08-26 10:20 UTC, halitbatur approved these changes

2021-08-26 10:20 UTC, merged