Sign Up modal
ReCoded-Org/capstone-turkey-animal-adoption pull request #38
Opened 2021-08-23 12:49 UTC by mustafaguldag

Hi, I have built sign up modal. I did upload Yup package for Formik(Rahaf and ayşe are using it). #22 
![image](https://user-images.githubusercontent.com/81811326/130449679-3ed64ac6-a9cf-4a14-9c92-b8f3055abb03.png)
![image](https://user-images.githubusercontent.com/81811326/130449719-6170722e-0239-47ef-8ad1-525036fff9d4.png)

2021-08-23 16:28 UTC, ayse8888 approved these changes
Hi Mustafa, the visual and the code seems nice !

2021-08-24 08:08 UTC, halitbatur requested changes
Good Work Mustafa! this branch need updates and conflicts needs to be merged

2021-08-24 08:08 UTC, halitbatur commented on src/components/NavBar/NavBar.js
> +  const [modalShow, setModalShow] = useState(false);
maybe a better state name here ?

2021-08-24 13:57 UTC, halitbatur requested changes

2021-08-24 13:57 UTC, halitbatur commented on src/components/NavBar/NavBar.js
> +  const [openModal, setOpenModal] = useState(false);
still the state name needs to be better maybe smth that relates to signUpModal ?

2021-08-25 07:10 UTC, halitbatur approved these changes
one more line and then its ready to be merged

2021-08-25 07:10 UTC, halitbatur commented on src/components/NavBar/NavBar.js
> +  const [showSignUp, setShowSignUp] = useState(false);
we need one extra line after this

2021-08-25 07:22 UTC, mustafaguldag commented on src/components/NavBar/NavBar.js
> +  const [showSignUp, setShowSignUp] = useState(false);
Thanks! I fixed that.

2021-08-26 09:46 UTC, merged