Resources Page
ReCoded-Org/capstone-turkey-animal-adoption pull request #41
Opened 2021-08-24 08:23 UTC by mustafaguldag

Hi, I did create the Resources Page. I did create data file which we need for resources page and import that to container page.  Also I added "Resources" link on the navbar so I did update navbar test as well. #34 
![image](https://user-images.githubusercontent.com/81811326/130582707-a0dcd179-e90a-4c35-baa4-772fbda4bc49.png)

2021-08-24 08:54 UTC, halitbatur approved these changes
LGTM

2021-08-25 20:28 UTC, ayse8888 approved these changes
hey mustafa, looks good to me. the code and visuals are nice. there is no extra lines

2021-08-26 08:29 UTC, Rofy87 requested changes
Can you change these please mustafa

2021-08-26 08:29 UTC, Rofy87 commented on src/App.js
> +      <Route exact path="/resources" component={ResourcesPage} />
Hi @mustafaguldag  please remove the exact no need for it 
and add a link in the navBar component for the resource

2021-08-26 08:29 UTC, Rofy87 commented on src/pages/resourcespage/ResourcesData.js
> +    id: "catAdoption",
text should me meaningful , you can take part of the text in the resource 
such as "Because adopting a new cat comes with a lot of change for both cat and cat parent, we’ve compiled a checklist to help make the transition as smooth as possible."
Please lets make this page ready for production not only dummy text for now since we are not going to use firebase for this one

2021-08-26 08:37 UTC, mustafaguldag commented on src/App.js
> +      <Route exact path="/resources" component={ResourcesPage} />
Hi, thanks for the review normally i added resources link(you can see in the picture) but dont know, something got wrong maybe i will do it again

2021-08-26 09:39 UTC, Rofy87 reviewed
Thanks @mustafaguldag  for the fast reply 
Looks good to me

2021-08-26 09:41 UTC, Rofy87 approved these changes

2021-08-26 09:46 UTC, merged